language: php

php:
    - '7.1'

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini

install:
    - composer install --prefer-dist -o --no-interaction

script:
    - ./bin/phpspec --no-interaction --format=dot run
